### ISSUE TITLE
pretrained models Link is failure and unavailable

### ISSUE THREAD

**Issue by sudohello** [calmevtime/DCTNet#1]
pretrained models Link is failure and unavailable

https://github.com/calmevtime1990/supp/tree/master/segmentation

https://drive.google.com/open?id=1UKmNORizsulH9E4awxjBR4fAlW1KlC5s

https://drive.google.com/open?id=14eTsI_LMjjQHyx_uOsb_DSy2pAIZFny-
https://drive.google.com/open?id=18WbbwpQuoAt--GMlZuWhNLjxN83A0g_i

https://drive.google.com/open?id=14eTsI_LMjjQHyx_uOsb_DSy2pAIZFny-
https://drive.google.com/open?id=18WbbwpQuoAt--GMlZuWhNLjxN83A0g_i

**Comment by calmevtime1990** [comment]
Links are renewed now. Thanks.
