### ISSUE TITLE
What's the difference between DCT in 8x8 patch and a parameter defined 8x8 convolution kernel?

### ISSUE THREAD

**Issue by maxenceliu** [calmevtime/DCTNet#2]
totally equals k=8, s=8, parameter defined layer

**Comment by maxenceliu** [comment]
totally equals k=8, s=8, parameter defined layer

**Comment by calmevtime** [comment]
You are correct from the computation perspective. But the result of DCT is more interpretable since different frequency components are separated. While the result of convolution is less interpretable since different frequency components are mixed.

**Comment by maxenceliu** [comment]
> You are correct from the computation perspective. But the result of DCT is more interpretable since different frequency components are separated. While the result of convolution is less interpretable since different frequency components are mixed.

DCT is definitely a certain form of convolution. This paper just use another way to explain convolution, because DCT are just kernels with orthogonality. The conclusion will mislead readers. This kind of decoration and ｌacking depth discussion will become a bluff in DL research. 

If this paper could deeply discuss the effectiveness of manual designed low level kernels (Such as DCT,　Haar-like, HOG, LBP...) with different parameters, it will be valuable.

**Comment by calmevtime** [comment]
You are correct that DCT is definitely a certain form of convolution. But our paper is not aiming to use another way to explain convolution. Instead, we explore the importance of each frequency component in several tasks. DCT is just a tool to transform data to the frequency domain. So please point out which conclusion is misleading readers, then we can discuss further. Thanks.

**Comment by maxenceliu** [comment]
> You are correct that DCT is definitely a certain form of convolution. But our paper is not aiming to use another way to explain convolution. Instead, we explore the importance of each frequency component in several tasks. DCT is just a tool to transform data to the frequency domain. So please point out which conclusion is misleading readers, then we can discuss further. Thanks.

**explore the importance of each frequency component** is more accurate than **Learning in the Frequency Domain**. But still needs further discussion.

**Comment by calmevtime** [comment]
Thanks for your suggestion.
