### ISSUE TITLE
no libturbojpeg.so file，only the libturbojpeg.dylib file？

### ISSUE THREAD

**Issue by cwwng** [calmevtime/DCTNet#22]
When installing libjpeg-turbo, I customized a write directory because I couldn't write to the dynamic library files in the build to DCMAKE_INSTALL_PREFIX=/usr and DCMAKE_INSTALL_DOCDIR=/usr/share/doc/libjpeg-turbo-2.0.3.
However, there is no libturbojpeg.so file under lib after writing to the directory, only the libturbojpeg.dylib file.
Should the TurboJPEG class load libturbojpeg.dylib?

Looking forward to your reply.
Thank you very much.

**Comment by jxhuang0508** [comment]
Hi, have you successfully installed libjpegturbo ? and could you please provide some info for how to install it?
