### ISSUE TITLE
why there are 2 parameters in the SE-like block?

### ISSUE THREAD

**Issue by zhezh** [calmevtime/DCTNet#3]
Hi,

In the paper, 
> Then, Tensor 3 is converted to Tensor 4 in Figure 4 of the shape 1 × 1 × C × 2 by multiplying every element in Tensor 3 with **two trainable parameters**. 

I am wondering why you use two parameters to calculate the `p` of the Bernoulli distribution.

In my view, one parameter will also work.
Could you explain the idea? Thanks~

**Comment by calmevtime** [comment]
We use a separate vector for representing 0 and 1, respectively. But using one vector should also work. Thanks.

**Comment by zhezh** [comment]
Thanks for quick reply.
